export const AREA_STATE = {
  DRAGGING: 'DRAGGING',
  CIRCLE_LEAVE_WHILE_DRAGGING: 'CIRCLE_LEAVE_WHILE_DRAGGING',
  CIRCLE_HOVER: 'CIRCLE_HOVER',
  LEGEND_HOVER: 'LEGEND_HOVER',
  NEUTRAL: 'NEUTRAL'
};

export const AREA_EVENT = {
  CIRCLE_ENTER: 'CIRCLE_ENTER',
  CIRCLE_LEAVE: 'CIRCLE_LEAVE',
  DRAGGING: 'DRAGGING',
  DRAGGING_END: 'DRAGGING_END'
};

export const RADIANS = 2 * Math.PI;
